const Cats = require('../models/cats')

const catBreeds = [
  {
      "Breed": "Abyssinian",
      "image": "https://cdn2.thecatapi.com/images/KWdLHmOqc.jpg",
      "description": "Ancient. Enigmatic. Athletic. The word you’re looking for is 'Abyssinian.' Currently one of the most popular breeds in the world, the Abyssinian, or Aby for short, is also one of the oldest, with origins shrouded in mystery. Lithe, strapping, and deeply curious, Abys are beloved by owners for their almost dog-like desire to socialize and follow their people around the house. They’re blessed with high intelligence and what seems like a motor that runs almost nonstop, making them natural explorers.\r\n\r\nColor Options: Red/Ginger , Blue/Gray, Cream, and Brown",
      "fur_length": "short",
      "color": "no_preference",
      "hypoallergenic": "neutral",
      "grooming": "monthly",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatibility": "yes",
      "child_compatibility": "yes"
  },
  {
      "Breed": "American Bobtail",
      "image": "https://cdn2.thecatapi.com/images/hBXicehMA.jpg",
      "description": "American bobtails are known for their short bobbed tails, rugged appearance, and playful personalities. They have been referred to as the “golden retriever” of cat breeds, thanks to their affectionate and friendly personalities. These cats love to be around humans and have a sweet, gentle nature that makes them wonderful companions. American bobtails are a relatively uncommon breed. Because they’re considered rare, these cats can cost around $600–$1,200 from a reputable breeder.\r\n\r\nColor Options: White, Black, Red/Ginger , Blue/Gray, Cream, and  Brown",
      "fur_length": "medium",
      "color": "no_preference",
      "hypoallergenic": "neutral",
      "grooming": "monthly",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "no",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "American Curl",
      "image": "https://cdn2.thecatapi.com/images/vJB8rwfdX.jpg",
      "description": "Proving that Bob Ross was right and there are such things as 'happy mistakes,'  the American curl is the result of a spontaneous, naturally occurring genetic mutation. Looking like any number of domestic cats, the thing that sets the breed apart is their ears, which curl towards the back of their heads. Underneath those unique ears lies a cat who is friendly, engaging, and incredibly sweet. Staying youthful well into adulthood, American curls are sometimes called the 'Peter Pan of the cat fancy.'\r\n\r\n\r\nColor Options: White, Black, Red/Ginger , Blue/Gray, Cream, and Brown",
      "fur_length": "medium",
      "color": "no_preference",
      "hypoallergenic": "non_allergic",
      "grooming": "weekly",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "American Longhair",
      "image": "https://i.pinimg.com/originals/11/55/ab/1155ab1db1bac12c6c6793fbe7d5f34b.jpg",
      "description": "The American longhair is not a specific cat breed, although aficionados are encouraging cat fancy associations to recognize this unique feline. For now, the term American longhair is used to indicate a cross between a Persian cat and an American shorthair cat. American longhair cats are typically medium-sized, reflecting the size and weight of their parents. Their coats come in a variety of colors and patterns and in varying degrees of thickness. There is sometimes confusion concerning the American longhair cat vs the Maine coon cat. This stems from the description of the Maine coon as America's original longhair cat.\r\n\r\nColor Options: White, Black, Red/Ginger , Blue/Gray, Silver, Cream, Tortishell, and Brown",
      "fur_length": "long",
      "color": "no_preference",
      "hypoallergenic": "allergic",
      "grooming": "weekly",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "American Shorthair",
      "image": "https://cdn2.thecatapi.com/images/MuEGe1-Sz.jpg",
      "description": "The direct descendants of European cats brought to the U.S. in the early 1600s, the American shorthair was originally prized for his uncanny ability to protect the grain harvests from rats and mice. People selected and bred these cats purely on their hunting ability. But, over time, their compact athletic bodies and boldly colored dense coats started to attract attention from pet-lovers. And, because these animals were also so intelligent and affectionate, they quickly caught hold with the American public, who began to invite them into their homes. \r\n\r\n\r\nColor Options: White, Black, Red/Ginger , Blue/Gray, Silver, Cream, Tortishell, and Brown",
      "fur_length": "short",
      "color": "no_preference",
      "hypoallergenic": "neutral",
      "grooming": "monthly",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "American Wirehair",
      "image": "https://cdn2.thecatapi.com/images/Q6TDnfM_O.jpg",
      "description": "The American wirehair cat is a breed native to New York, with a wiry, crimped coat resulting from a natural genetic mutation. Their eye-catching wavy hair is this breed’s defining quality. These cats are loving, easygoing, and affectionate companion animals. Like true New Yorkers, these kitties have an independent streak that makes them a great fit for owners with busy lifestyles. American wirehairs are fairly rare, despite the fact that the breed is relatively well-known. These cats typically cost between $800–$1,200 from a breeder, depending on pedigree. If you’re looking for a new family pet, or simply want to learn more about this breed, here’s everything you need to know about American wirehair cats and kittens.\r\n\r\n\r\nColor Options: White, Black, Red/Ginger , Blue/Gray,  Cream, Tortishell, and Brown\r\n",
      "fur_length": "short",
      "color": "no_preference",
      "hypoallergenic": "neutral",
      "grooming": "monthly",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "Balinese",
      "image": "https://cdn2.thecatapi.com/images/DBmIBhhyv.jpg",
      "description": "The Balinese cat is a variation on the traditional Siamese cat breed that features everything people love about the older breed, but in a furrier package. The long, silky coat of the Balinese cat is the hallmark of the breed. Indeed, it’s the very reason for the breed’s existence. Coat notwithstanding, Balinese are everything you know and love about the Siamese: playful, highly intelligent, incredibly devoted to their family units, and active, engaging talkers. \r\n\r\nColor Options:  Black,  Blue/Gray, Cream, and Brown",
      "fur_length": "long",
      "color": "no_preference",
      "hypoallergenic": "allergic",
      "grooming": "periodically",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "no",
      "child_compatability": "yes"
  },
  {
      "Breed": "Bengal",
      "image": "https://cdn2.thecatapi.com/images/J2PmlIizw.jpg",
      "description": "The first time you see a Bengal cat roaming through your house, you might think a jungle cat has broken in. That's because this spectacular breed sports a spotted or marbled coat that looks a lot like a wild leopard or ocelot. But the Bengal is anything but wild, and has a loving, affectionate personality. While Bengals were developed by breeding domestic felines to an Asian leopard cat, their wild natures have long been abandoned. Bengal cats were first accepted as a breed in 1983, and since then this handsome cat has skyrocketed in popularity. Like some other hybrid breeds, such as the Savannah cat, Bengal cats are classified by how many generations they are removed from their original wild parent.",
      "fur_length": "short",
      "color": "brown",
      "hypoallergenic": "neutral",
      "grooming": "weekly",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "no",
      "child_compatability": "yes"
  },
  {
      "Breed": "Birman",
      "image": "https://cdn2.thecatapi.com/images/C0BNiXO0T.jpg",
      "description": "Originally called the Sacred Cat of Burma, the Birman is an ancient breed that’s been prized for generations for its beautiful markings and its lovely, mild temperament. These mid-size cats are sociable, easy-going felines that make wonderful pets for people of all ages. It's hard to describe perfection, but Birman cats come pretty close. An ancient member of the cat clan, Birmans (originally known as the Sacred Cat of Burma) have been charming people for centuries. Once beloved by temple monks, these walking beauties have become popular pets around the globe. Birmans are a mid-size breed with a lush, cream-color coat with darker points, white-gloved paws, and sparkling blue eyes. Yet, for all their glamour, Birman cats are anything but finicky. They're always outgoing, friendly, and easy-to-care-for cats.\r\n\r\nColor Options:  Black, Red/Ginger , Blue/Gray, Cream, and Brown",
      "fur_length": "long",
      "color": "no_preference",
      "hypoallergenic": "allergic",
      "grooming": "monthly",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "Bombay",
      "image": "https://cdn2.thecatapi.com/images/BkksyH95Z.jpg",
      "description": "Want a panther, but also enjoy both of your arms? The Bombay cat breed is the kitty for you! Bred specifically to look like the Indian black panther, the Bombay is a mix of the Burmese and the black American shorthair. The result is a cat that does indeed resemble the big jungle cat, without having a single drop of wild blood in his pedigree. Combining some of the best traits of both parent breeds, the Bombay has the hardiness, loyalty, and intelligence of the Burmese without being quite as overwhelmingly vocal and while sporting a gorgeous, solid black coat.",
      "fur_length": "short",
      "color": "black",
      "hypoallergenic": "neutral",
      "grooming": "periodically",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "British Longhair",
      "image": "https://cdn2.thecatapi.com/images/7isAO4Cav.jpg",
      "description": "British Longhair cats are loyal, loving pets with sweet faces and relaxed attitudes. Learn more about life with this friendly, fluffy cat breed. The British Longhair is a sweet tempered, round-faced teddy bear of a cat. These fluffy felines originated in Britain and are a cross between the British Shorthair and Persian cat breeds. The British Longhair has technically been around for centuries, but has only recently been recognized as its own breed. These adorable cats are affectionate, loyal, and undemanding. If you're looking for a family cat or devoted companion to keep you company without being especially needy, the British Longhair makes a great choice.\r\n\r\nColor Options: White, Black, Red/Ginger , Blue/Gray, Cream, and Brown",
      "fur_length": "long",
      "color": "no_preference",
      "hypoallergenic": "allergic",
      "grooming": "weekly",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "British Shorthair",
      "image": "https://cdn2.thecatapi.com/images/xNuSF5YWY.jpg",
      "description": "British shorthair cats are one of the oldest recognized cat breeds, first thought to have been brought to Britain by the Romans. Prized for their soft, plush coats and rounded bodies, British shorthairs could almost be mistaken for living teddy bears. One of the most popular cat breeds in the world, the British shorthair is appropriately named. Not only do they have a thick, plush short coat, they also have a friendly yet no-nonsense—that is, rather British—sensibility about life. British shorthairs make ideal family cats and enjoy being with their owners, but may turn up their noses at being held or cuddled too much. This beautiful breed comes in a wide variety of colors and patterns, but the traditional British shorthair is wrapped in blue fur. The best part: This medium-to-large-sized cat has few health problems.\r\n\r\nColor Options: White, Black, Red/Ginger , Blue/Gray, Tortishell, Cream, and Brown",
      "fur_length": "short",
      "color": "no_preference",
      "hypoallergenic": "neutral",
      "grooming": "weekly",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "Burmese",
      "image": "https://cdn2.thecatapi.com/images/4lXnnfxac.jpg",
      "description": "With their huge eyes, outgoing personalities, and dog-like tendencies, Burmese are the perfect cat for winning over people who say they don’t like cats. It's really hard not to immediately like Burmese cats. Intelligent, playful little dynamos, Burmese are incredibly social to humans and will quickly learn to play interactive games like fetch or tag. They also make excellent ambassadors for any self-professed \"non-cat people,\" thanks to their affectionate, almost dog-like personalities and their giant, expressive eyes that make Burmese cats look like they were ripped straight out of a Margaret Keane painting.\r\n\r\nColor Options: Red/Ginger , Blue/Gray, Cream, Tortishell, and Brown",
      "fur_length": "short",
      "color": "no_preference",
      "hypoallergenic": "neutral",
      "grooming": "periodically",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "Burmilla",
      "image": "https://cdn2.thecatapi.com/images/p2U4ZXgKL.jpg",
      "description": "Burmillas are a cross between chinchilla Persians and Burmese cats. These cats are a fun, friendly breed that loves to be part of the family. The Burmilla is easygoing, affectionate, and social. These beautiful cats are a cross between chinchilla Persian and Burmese cats, which results in Burmillas’ outgoing but laid-back personalities. \r\nThis breed is known for a super-soft coat and bright green eyes. Burmillas need only minimal care and get along with everyone, so they make great first pets and family pets. \r\nBurmillas came into existence in the 1980s and still remain relatively rare. Because of their rareness and complicated four-generation breeding process, Burmilla kittens typically cost between $800–$1,200 from a reputable breeder.\r\n\r\nColor Options: Black, Red/Ginger , Blue/Gray, Cream, and Brown",
      "fur_length": "short",
      "color": "no_preference",
      "hypoallergenic": "neutral",
      "grooming": "periodically",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "California Spangled",
      "image": "https://cdn2.thecatapi.com/images/B1ERTmgph.jpg",
      "description": "California Spangled cats are a crossbreed of many strains, including the Abyssinian, American Shorthair and British Shorthair. Despite their wild appearance, they are completely domestic.\r\n\r\n\r\nColor Options: White, Black, Blue/Gray, Red/Ginger, and Brown",
      "fur_length": "short",
      "color": "no_preference",
      "hypoallergenic": "neutral",
      "grooming": "periodically",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "California Rex",
      "image": "https://pictures-of-cats.org/wp-content/uploads/2019/01/California-Rex.jpg",
      "description": "The Californian Rex is from the United States. Considered as a relatively new breed, they are currently quite rare. As its name indicates, the Californian Rex was first seen in California in the 1960's. It is a close cousin of the Cornish Rex, the difference being that it has medium length hair. This breed of cat is quite rare, making it quite difficult to know its true origins. There is so little known about the breed, that it isn't allowed to participate in feline competitions. The LOOF recognises it as a \"new breed\".\r\n\r\nColor Options: White, Black, Blue/Gray, Red/Ginger, and Brown",
      "fur_length": "long",
      "color": "no_preference",
      "hypoallergenic": "allergic",
      "grooming": "periodically",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "Ceylon",
      "image": "https://cdn.wamiz.fr/cdn-cgi/image/quality=80,width=1200,height=675,fit=cover/https://cdn.wamiz.fr/animal/breed/cat/adult/5cd0279a1ded1873830657.jpg",
      "description": "The Ceylon originates, as its name suggests, from the island of Ceylon, which has since become part of Sri Lanka. They arrived in Europe for the first time in 1984 in Milan (Italy). They are an extremely rare breed and only a few individual Ceylon cats can currently be found in Italy and France. The breed recognised by the International Feline Federation until 1993. They are active cats, that love coconut pulp, just affirming their tropical origins!\r\n\r\n\r\nColor Options: Black, Blue/Gray, Red/Ginger,  and Brown",
      "fur_length": "short",
      "color": "no_preference",
      "hypoallergenic": "neutral",
      "grooming": "periodically",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "Chartreux",
      "image": "https://cdn2.thecatapi.com/images/EYtB_5RrB.jpg",
      "description": "Chartreux cats are as quiet and calm as they are silly and personable. Learn more about this fun French breed. The Chartreux (pronounced shar-true) has been around for centuries. These cats are known for their short, blue-gray coats and quiet demeanor. This undemanding breed is calm, independent, and at times silly. If you would relish the company of a sweetly silent companion—and you're open to interpreting her mimed body language—the Chartreux makes a wonderful pet. These cats are somewhat rare today. Because of that, Chartreux kittens usually cost around $1,000–$1,500, depending on age, pedigree, and other factors.",
      "fur_length": "short",
      "color": "blue",
      "hypoallergenic": "neutral",
      "grooming": "weekly",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "Chausie",
      "image": "https://cdn2.thecatapi.com/images/5i_-8rPKS.jpg",
      "description": "The Chausie is a domestic breed of cat that was developed by breeding a few indiviuals from the non-domestic species jungle cat to a far greater number of domestic cats. First recognized as a cat in 1995, it is categorized as a non-domestic hybrid breed.",
      "fur_length": "short",
      "color": "brown",
      "hypoallergenic": "neutral",
      "grooming": "monthly",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "no",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "Chinchilla Persian",
      "image": "https://cf.ltkcdn.net/cats/images/std/144820-480x323r1-Chinchilla-Persian-cat-3.webp",
      "description": "The Chinchilla cat breed is really a specific type of Persian cat. The breed comes in one colour - a pure white coat that is subtly tipped with black to produce a silvery sheen. Its emerald green eyes are distinctively lined with black. The Chinchilla cat breed was the first cat to have been selectively bred for a specific colour. It was first shown in 1894 in Crystal Palace, London.",
      "fur_length": "long",
      "color": "white",
      "hypoallergenic": "allergic",
      "grooming": "weekly",
      "energy": "no",
      "playful": "no",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "Cornish Rex",
      "image": "https://cdn2.thecatapi.com/images/DmP9GCClC.jpg",
      "description": "With their unique, eye-catching appearance, Cornish rex cats are perfect for people with avant garde tastes. With their long, slender, delicate-looking bodies, large eyes and huge ears, the Cornish rex is a cat sure to spark conversation. But their most noteworthy calling card is their coat. The Cornish rex lacks the long hair of an outer coat, leaving them with just a curly, soft down undercoat.\r\n\r\nColor Options: White, Black, Blue/Gray, Red/Ginger, Tortishell, and Brown",
      "fur_length": "short",
      "color": "no_preference",
      "hypoallergenic": "neutral",
      "grooming": "periodically",
      "energy": "no",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "Cymric",
      "image": "https://cdn2.thecatapi.com/images/3dbtapCWM.jpg",
      "description": "The Cymric is a medium-sized cat that is stocky and heavily boned. The Cymric can appear larger than she is or you may not realize how heavy she can actually be when she is fully mature. Not every Cymric is completely tailless. On a completely tailless Cymric, no protuberance can be felt. These cats are called rumpies. Some Cymric are called Stumpies as these cats have a small stump of a tail. Others are called rumpy risers because when your hand goes down around the rump, it causes the small tail to rise. As a rumpy riser ages, this little tail may be covered by a fat pad and will no longer rise when petted. Some Cymric kittens are born with full tails, and some are born with half tails.\r\n\r\nColor Options: White, Black, Blue/Gray, and Red/Ginger",
      "fur_length": "long",
      "color": "no_preference",
      "hypoallergenic": "allergic",
      "grooming": "weekly",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "Devon Rex",
      "image": "https://cdn2.thecatapi.com/images/Zhv2xfZFH.jpg",
      "description": "Devon rex cats are known as “poodle cats,” thanks to their wavy coats and intelligent, outgoing personalities. Learn more about owning a Devon rex cat. The Devon rex cat is visually striking and known for their impish faces, tall ears, and slender frames. These wide-eyed cats love to play, climb and clown around. They’re a great fit for active owners with lots of time and attention to give. These super social cats absolutely adore people and love making friends. The Devon rex is a relatively uncommon breed. Potential owners can expect to spend $600–$1000 for a Devon rex kitten from a quality breeder.\r\n\r\nColor Options: Black, Brown, Red/Ginger, Cream, and Blue",
      "fur_length": "short",
      "color": "no_preference",
      "hypoallergenic": "non_allergic",
      "grooming": "periodically",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "Donskoy",
      "image": "https://cdn2.thecatapi.com/images/KWVenr3Pq.jpg",
      "description": "The Donskoy cat, also known as Don Sphynx or Russian Hairless, is a hairless cat breed of Russian origin. It is not related to the better-known Sphynx cat, also known as the Canadian Hairless, whose characteristic hairlessness is caused by a recessive mutation in the keratin 71 gene. The Donskoy's hairlessness, on the other hand, is caused by a dominant mutation.\r\n\r\nColor Options: Black, Brown, White, Red/Ginger, Cream, and Blue/Gray",
      "fur_length": "no_hair",
      "color": "no_preference",
      "hypoallergenic": "non_allergic",
      "grooming": "monthly",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "Egyptian Mau",
      "image": "https://cdn2.thecatapi.com/images/uygraw0_D.jpg",
      "description": "The elegantly spotted Egyptian mau is a lean, athletic cat with a history dating back at least 3,000 years. Regal and intelligent, this rare breed is social but doesn’t need constant attention. When you see cats depicted in ancient Egyptian art, you’re looking at the more-or-less direct-line ancestor of the Egyptian mau. Cats with a noble heritage and an appearance that’s reminiscent of its ancient, feral past, the Egyptian mau is the only naturally occurring breed of spotted domestic cat recognized by the Cat Fanciers Association (CFA). Striking to look at and as beautiful as it is rare, the Egyptian mau is a breed that stirs the imagination with its shiny, spotted coat and gorgeous, gooseberry green eyes.\r\n\r\nColor Options: Black, Brown, and Red/Ginger",
      "fur_length": "short",
      "color": "no_preference",
      "hypoallergenic": "neutral",
      "grooming": "periodically",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "Europeann Shorthair",
      "image": "https://s36537.pcdn.co/wp-content/uploads/1970/01/GettyImages-1072769156.jpg.optimal.jpg",
      "description": "European shorthair cats are adaptable, friendly, people-pleasing pets who love to hunt and spend time with their pet parents. Learn more about the European shorthair cat breed. One of the oldest European cat breeds, the European shorthair is the pedigreed standard of the common European house cat. These felines have round faces, medium-size bodies, and short, shiny coats of thick hair. Known for their adaptable attitudes and friendly personalities, this cat breed also has excellent mousing abilities. When it comes to house cats, this breed is pretty easy to please. European shorthairs’ low-maintenance personalities and easy grooming requirements make them a great fit for first-time owners. While the European shorthair is one of the most popular European cat breeds, it remains relatively rare in the rest of the world.\r\n\r\nColor Options: Black, White, Blue/Gray, and Red/Ginger",
      "fur_length": "short",
      "color": "no_preference",
      "hypoallergenic": "allergic",
      "grooming": "monthly",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "Exotic Shorthair",
      "image": "https://cdn2.thecatapi.com/images/khyg1KLOZ.jpg",
      "description": "Often called the “lazy man’s Persian” the exotic shorthair has the same body type and personality of the Persian cat, but with a shorter coat. Find out everything you need to know about this docile cat breed. If you’ve always wanted a Persian cat, but were concerned about the time it takes caring for their long coats, then an exotic shorthair might be for you. This sweet and loving breed has the looks and personality of a Persian, but it sports an undemanding short, dense coat that’s a snap to maintain. In fact, a weekly brushing is all an Exotic Shorthair really needs to keep it in top form. Exotic shorthair cats also come in the same wide range of colors and patterns as Persians. \r\n\r\nColor Options: Black, Brown, White, Red/Ginger, Cream, and Blue/Gray",
      "fur_length": "short",
      "color": "no_preference",
      "hypoallergenic": "neutral",
      "grooming": "monthly",
      "energy": "no",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "German Rex",
      "image": "https://dnl7t01l0fo05.cloudfront.net/fr/wp-content/uploads/sites/2/2018/04/chat-german-rex.jpg",
      "description": "The German Rex is a small to medium-sized cat, and because she stands so high on her legs she can appear to be a large cat. Because of the fine boning on the German Rex, she may feel almost dainty, but this cat is athletic and not at all fragile. The German Rex has a round head with large ears and eyes that look large for the size of the head. She has a strong chin and long, slender legs. The tail is also medium in length, and is well covered with fur. The coat on the German Rex is unusual as it has no guard hairs, is silky, short and curls naturally. The whiskers also curl. \r\n\r\nColor Options: Black, White, Cream, and Red/Ginger",
      "fur_length": "short",
      "color": "no_preference",
      "hypoallergenic": "non_allergic",
      "grooming": "monthly",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "Havana",
      "image": "https://cdn2.thecatapi.com/images/eJUcA5Wt-.jpg",
      "description": "The Havana Brown was the result of a planned breeding between Siamese and domestic black cats, by a group of cat fanciers in England, in the 1950s. Early breeders introduced a Siamese type Russian Blue into their breeding. However, using current genetic testing, it is believed that almost none remain in the gene pool. It has been documented that self-brown cats were shown in Europe in the 1890s, one name given to these was the Swiss Mountain Cat. These disappeared until post-World War II, with the most likely explanation that the Siamese Cat Club of Britain discouraged their breeding. The Swiss Mountain Cat was never used in the breeding programs of the modern Havana Brown. However, they likely share genetics inherited from the Siamese.",
      "fur_length": "short",
      "color": "brown",
      "hypoallergenic": "neutral",
      "grooming": "monthly",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "Himalayan",
      "image": "https://cdn2.thecatapi.com/images/wu8gMdmfo.jpg",
      "description": "Himalayans combine the luxurious coat of a Persian with the flashy coloring of a Siamese. Although he’s a mid-sized cat, the Himalayan looks larger than he is because of his fluffy, long coat. A mix between the Persian and the Siamese, the Himalayan is a long-haired beauty. Also called the colorpoint Persian, these cats are easy to recognize by their smooshy flat faces, long fur, and signature markings. And these cats aren't just looks—they're easygoing, laid-back, and described as 'dog-like' in that they are extremely affectionate toward the humans they love.\r\n\r\nColor Options: Black, Blue/Gray, Red/Ginger, Brown, and White",
      "fur_length": "long",
      "color": "no_preference",
      "hypoallergenic": "allergic",
      "grooming": "weekly",
      "energy": "no",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "Japanese Bobtail",
      "image": "https://cdn2.thecatapi.com/images/CrZtoDsgj.jpg",
      "description": "Japanese bobtail cats are known for their short tails and playful personalities. This breed makes wonderful family pets. Japanese bobtails are prized for their short, kinked tails, outgoing personalities, and athletic abilities. This captivating breed is native to Japan but known around the world. These energetic animals make wonderful pets and are especially good with children. They love to be the center of attention and a huge part of family life. They’re low-shedding, easy to groom, and super intelligent. These cute, quirky cats are relatively rare. Because Japanese bobtail cats are uncommon, they typically cost between $600–$1,600 from a responsible breeder.\r\n\r\nColor Options: Black, Brown, White, Tortishell,  Red/Ginger, Blue/Gray, and Cream",
      "fur_length": "all",
      "color": "no_preference",
      "hypoallergenic": "allergic",
      "grooming": "monthly",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "Javanese",
      "image": "https://cdn2.thecatapi.com/images/cua3trGPU.jpg",
      "description": "The Javanese is highly intelligent, agile and athletic, and loves to play. The Javanese is a longhaired variety of Siamese dressed in Colorpoint colors. He was developed from a foundation of Siamese, Colorpoint and Balinese cats. The cats do not actually come from Java but were whimsically given the name because Java is a sister island to Bali, which was a nice touch, given the breed’s relationship to the Balinese (which does not come from Bali, by the way). \r\n\r\nColor Options: Black, Brown, White, Red/Ginger, Blue/Gray, and Cream",
      "fur_length": "long",
      "color": "no_preference",
      "hypoallergenic": "allergic",
      "grooming": "monthly",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "Khao Manee",
      "image": "https://cdn2.thecatapi.com/images/165ok6ESN.jpg",
      "description": "Khao Manee cats, also known as Khao Plort cats, are playful. They have pure white coats and jewel-tone eyes. These rare kitties are said to bring good luck to owners. Khao Manee (pronounced 'cow-muh-nee')—also known as White Gem, Khao Plort, and Diamond Eye cats—hail from Thailand, where they’re considered an ancient breed and harbingers of good luck. These cats are known for their snow-colored coats, jewel-tone eyes, and athletic bodies. These lucky charms are outgoing, playful pets who are totally dedicated to their humans. These cats thrive on attention, and they usually get a ton of it, thanks to their striking appearance and social nature. Khao Manees make loving family pets and great companions for children.",
      "fur_length": "short",
      "color": "white",
      "hypoallergenic": "neutral",
      "grooming": "periodically",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "Korat",
      "image": "https://cdn2.thecatapi.com/images/DbwiefiaY.png",
      "description": "Regal in bearing and possessing a stunning, shimmering blue coat, the Korat is a gorgeous, affectionate “good luck cat” for most households.  The Korat is one of the oldest, most stable breeds in the world. Revered in their native Thailand as a 'good luck cat,' Korats are traditionally given in pairs, with special importance when given to brides as wedding gifts. It can be easy to see why the breed has been beloved in their homeland for so many centuries. Korats have one of the most beautiful coats in all the cat kingdom and are intelligent, loving lap cats who develop strong bonds with their families.",
      "fur_length": "short",
      "color": "blue",
      "hypoallergenic": "neutral",
      "grooming": "weekly",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "LaPerm",
      "image": "https://cdn2.thecatapi.com/images/VuxDCG8hV.jpg",
      "description": "LaPerm cats are known for their curly coats, friendly personalities and loud, proud purring. LaPerm cats are charming and curly-haired with gentle, affectionate personalities. Their wavy coat is the result of a mutated gene that was discovered in the 1980s, making them a relatively new breed. This breed's loving, lap cat tendencies and low-maintenance coat make them an easy, cuddly breed to live with. LaPerms make wonderful companion pets and adore every moment with their beloved humans. LaPerm cats typically cost between $300-$600 from a reputable breeder.\r\n\r\nColor Options: Black, Brown, White, Cream, Tortishell, and Blue/Gray",
      "fur_length": "all",
      "color": "no_preference",
      "hypoallergenic": "allergic",
      "grooming": "weekly",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "Maine Coon",
      "image": "https://kittentoob.com/wp-content/uploads/2014/11/Big-Maine-Coon.jpg",
      "description": "Maine coons are large, intelligent, affectionate pets who love their people. Maine coons are large, affectionate cats who love to play and hang out with their humans. This cat breed is typically known for its massive size—up to 40 inches in length—but Maine coon owners know and prize these cats for being loving family pets. Maine coons are surprisingly popular, especially considering at one point this breed almost faced extinction. In 2019, the Cat Fanciers' Association listed the Maine coon as the fifth-most popular cat breed. The average Maine coon kitten costs between $400 and $1,500, depending on pedigree. \r\n\r\nColor Options: Black, White, Red/Ginger, Tortishell,  and Blue/Gray\r\n",
      "fur_length": "long",
      "color": "no_preference",
      "hypoallergenic": "allergic",
      "grooming": "weekly",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "Manx",
      "image": "https://cdn2.thecatapi.com/images/Rscv6E1c5.jpg",
      "description": "With his noteworthy tailless body and sweet disposition, the Manx is a national treasure on the Isle of Man and a longtime favorite in the cat fancy. Manx cats are kind of like the diet sodas of the cat fancy: all the great cat flavor you love, now with up to 100 percent less tail. The result of a naturally occurring genetic mutation that shortens the tail, the Manx has been the dominant cat breed on Britain's Isle of Man, a small island in the Irish Sea, for centuries. Known for their gentle, unassuming, sweet dispositions and their legendary hunting abilities, Manx have been favorites of sailors and farmers for almost as long as they've been around.\r\n\r\nColor Options: Black, Brown, White, Blue/Gray, and Red/Ginger",
      "fur_length": "shot",
      "color": "no_preference",
      "hypoallergenic": "neutral",
      "grooming": "weekly",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "Munchkin",
      "image": "https://cdn2.thecatapi.com/images/a1g4Ycw-z.jpg",
      "description": "Munchkin cats are short on legs and big on personality. Learn more about this incredibly cute one-of-a-kind cat breed. Munchkin cats are quick, energetic, fun-loving, and affectionate. What they lack in leg length they more than make up for with their unique look and loving temperament. The Munchkin, as you may have guessed from her name, is on the short side. She's actually unique among dwarf cat breeds—this petite kitty actually fits all the other size indicators of a normal adult-sized cat, except for their little legs. Never heard of a Munchkin? That's probably because they're relatively new, having been legitimized by The International Cat Association as their own breed in the early 2000s.\r\n\r\nColor Options: Black, Brown, Red/Ginger, Cream, Blue/Gray, and White",
      "fur_length": "all",
      "color": "no_preference",
      "hypoallergenic": "neutral",
      "grooming": "weekly",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "Nebelung",
      "image": "https://cdn2.thecatapi.com/images/GwRBXx7-w.jpg",
      "description": "Nebelungs are beautiful, loving, loyal cats who thrive on stability and routine. Sometimes mistaken for a Russian blue, the nebelung shares that breed’s long, solid blue coat and approximate size. Indeed, though a genetically separate breed, the Russian blue is still an acceptable outcross for pedigreed nebelungs. Created in the United States in the 1980s, the nebelung is a rare breed that has become prized for its long, soft coat and understated, mild-mannered personality.",
      "fur_length": "long",
      "color": "blue",
      "hypoallergenic": "allergic",
      "grooming": "weekly",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "no"
  },
  {
      "Breed": "Norwegian Forest",
      "image": "https://cdn2.thecatapi.com/images/wJyw82pIl.jpg",
      "description": "Norwegian forest cats are large, loving animals who make excellent family pets. Learn more about this friendly, gentle cat breed. Norwegian forest cats are large, loving felines affectionately nicknamed 'Wegies' by fans of the breed. Wegies are popular across the world and especially adored in their native land of Norway, where they go by the name skogkatt. These kind kitties make amazing pets and are instantly recognizable by their huge size and calm and gentle temperament. Norwegian forest cats are affectionate, undemanding companions. If you can provide lots of love, attentive brushing, and safe surfaces for your cat to climb, the Wegie will make an amazing family pet.\r\n\r\nColor Options: Black, White, Cream, and Blue/Gray",
      "fur_length": "long",
      "color": "no_preference",
      "hypoallergenic": "allergic",
      "grooming": "weekly",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "Ocicat",
      "image": "https://cdn2.thecatapi.com/images/JAx-08Y0n.jpg",
      "description": "Meant to emulate wild ocelots, the ocicat brings the visual thrill of a big cat, without a drop of wild blood. The ocicat was created to do exactly what its name implies: resemble an ocelot! Similar to breeds such as the toyger or the Bombay, the ocicat was bred to mimic the appearance of a large wild cat, but without a drop of wild DNA in the cat’s makeup. With its remarkable spotted coat, the ocicat is a one-of-a-kind conversation starter. These cats have highly social personalities, keen minds, and dispositions that have been described as 'dog-like.'\r\n\r\nColor Options: Black, Blue/Gray,  Cream, and Brown\r\n",
      "fur_length": "short",
      "color": "no_preference",
      "hypoallergenic": "neutral",
      "grooming": "monthly",
      "energy": "yes",
      "playful": "yes",
      "affection": "no",
      "independence": "no",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "Oriental Shorthair",
      "image": "https://cdn2.thecatapi.com/images/LutjkZJpH.jpg",
      "description": "Oriental shorthairs are friendly, intelligent, and inquisitive cats that love being around people and fellow furry friends. Learn more about living with this eye-catching breed. Oriental shorthairs don't just enter a room: They command it. From their large ears and angular faces to their long, slender frames, these stunning cats only look like they'd be standoffish. Their friendly, loving personality is quite the opposite.  \r\n\r\nColor Options: Black, Blue/Gray, Red/Ginger, Cream, White, and Brown",
      "fur_length": "short",
      "color": "no_preference",
      "hypoallergenic": "allergic",
      "grooming": "weekly",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "Persian",
      "image": "https://cdn2.thecatapi.com/images/3Pem6K30P.jpg",
      "description": "Sweet tempered and loving, Persian cats are famous for their long, flowing coats and round, pansy-like faces. As one of the most recognized and adored cat breeds on the planet, Persian cats have been happily snuggling up with their owners since the 1600s. With their long, flowing coats; thick bodies; and flat faces, it's hard to resist the charm of a Persian. Persian cats are a medium-sized breed and take their role as a loving companion seriously-they're always ready to be stroked and fussed over on a moment's notice. This beautiful kitty comes in a wide variety of colors and color combos, and they get along with all family members (including fellow furry ones) when introduced as kittens. If you're willing to put in the work with grooming-and it's a lot of work-you won't find a more loving companion.\r\n\r\nColor Options: Tortishell, Black, Brown, White, Red/Ginger, Cream, and Blue/Gray",
      "fur_length": "long",
      "color": "no_preference",
      "hypoallergenic": "allergic",
      "grooming": "weekly",
      "energy": "no",
      "playful": "no",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "Peterbald",
      "image": "https://www.thesprucepets.com/thmb/xCBYNz_e7zQjy5QG22uGSFIAjnc=/1500x1040/filters:fill(auto,1)/GettyImages-888877908-aaa9d6ad3dc0436695cd8ee42f006b8e.jpg",
      "description": "Similar in size and appearance to the sphynx or Oriental shorthair, the Peterbald cat is a newer breed of Russian origin with a unique coat and devoted family disposition. A relatively new breed of cat, the Peterbald is a Russian-bred cat with a very complicated relationship with fur. Coming in a variety of coat colors and patterns, the Peterbald can have a coat of short hair, fine peach fuzz, or no hair—all of which can change throughout the cat’s lifetime. But don’t let the coat fool you, these cats aren’t just a visual novelty. The Peterbald is a loving, affectionate, deeply loyal family cat breed that develops strong bonds with people and loves the company of other animals. While you may not think that a hairless cat would need to be groomed, Peterbalds need weekly baths!\r\n\r\nColor Options: Black, Brown, White, Red/Ginger, and Blue/Gray",
      "fur_length": "no_hair",
      "color": "no_preference",
      "hypoallergenic": "non_allergic",
      "grooming": "weekly",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "Pixiebob",
      "image": "https://cdn2.thecatapi.com/images/4MEAQffKS.jpg",
      "description": "The Pixie-bob is a muscular, highly intelligent cat with a sweet and loyal personality that makes him a great family pet. A large, muscular cat, the Pixie-bob is rumored to originate from a tryst between a domestic shorthair and a bobcat. The breed does resemble their wild cousins, but DNA testing shows they are a wholly domestic cat with a sweet, affable personality and a dog-like loyalty to their family units. Pixie-bobs enjoy learning tricks and playing games like fetch. They’re always down to eat a meal or two, anytime you are. Similar to breeds like the Bombay, toyger, or ocicat, Pixie-bobs can feel like wild cats in some ways, but without any of the unnecessary risk to their owners.  ",
      "fur_length": "all",
      "color": "brown",
      "hypoallergenic": "neutral",
      "grooming": "monthly",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "Ragamuffin",
      "image": "https://cdn2.thecatapi.com/images/--YZl1YWO.jpg",
      "description": "Beautiful, fuzzy, gentle giants, the RagaMuffin is the perfect family cat. She loves being held and stroked, and she gets along famously with children and other pets. The RagaMuffin is a big kitty. Big eyes, big body, big heart. They're a perfect choice for a family house cat because they adore the company of people, get along well with other pets, and seem to have an endless amount of patience for children's antics. One of the newer cats in the registry of the Cat Fanciers Association (CFA), the RagaMuffin is the lap cat for people who would love to find a way to combine a house cat with a weighted blanket.\r\n\r\nColor Options: Tortishell, Black, Brown, White, Red/Ginger, and Blue/Gray",
      "fur_length": "long",
      "color": "no_preference",
      "hypoallergenic": "neutral",
      "grooming": "monthly",
      "energy": "no",
      "playful": "no",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "Ragdoll",
      "image": "https://cdn2.thecatapi.com/images/oGefY4YoG.jpg",
      "description": "Ragdoll cats are gentle, loving companion pets who get along great with children. Ragdolls are large, lovable cats who are incredibly patient and gentle. Despite their imposing size, these cats are a calm and quiet breed who love nothing more than playing and cuddling with their pet parents. This breed is typically easy to care for and incredibly social. They make great family pets and get along well with children. If you have the time and attention to give this fluffy kitty, she will reward you with endless loyalty and love. Because ragdolls require careful breeding, they're less common than other breeds of cats. Ragdoll prices can vary from $400 for a kitten to as high as $2,000 for a show cat. The cost of your cat will depend on age and pedigree.\r\n\r\nColor Options: Black, Brown, White, Red/Ginger, Cream, and Blue/Gray",
      "fur_length": "long",
      "color": "no_preference",
      "hypoallergenic": "allergic",
      "grooming": "weekly",
      "energy": "no",
      "playful": "no",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "Russian Blue",
      "image": "https://cdn2.thecatapi.com/images/S-1YzA7-_.jpg",
      "description": "Russian blues are intelligent, loving, and loyal cats while preserving their independent streak. Russian blues are known for their thick, gorgeous blue-gray coat and bright eyes. These cats are sweet, loyal, and cautious animals who love having a routine. A loving temperament, independent streak, and low grooming requirements make the Russian blue a great family pet. If you have the patience to socialize this shy kitty, you'll gain an affectionate family member who is totally devoted to you. The Russian blue is a fairly common breed, and kittens from a reputable breeder typically cost between $400–$600.",
      "fur_length": "short",
      "color": "blue",
      "hypoallergenic": "neutral",
      "grooming": "weekly",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "Savannah",
      "image": "https://cdn2.thecatapi.com/images/a8nIYvs6S.jpg",
      "description": "Savannah cats are a large, athletic breed that’s especially affectionate with their owners, but can be a bit standoffish with strangers. Tall and elegant, the Savannah cat was first introduced in the late 20th century. Savannahs are actually a hybrid breed, the result of breeding a Siamese cat with a wild serval. And that wildness is on full display: The breed retains the large perked ears, long legs, and spotted coat of its African cat heritage, while keeping the friendly demeanor of a domestic pet. One thing to know about Savannahs: These kitties are big. Adult Savannah cats can grow up to 17 inches tall and weigh 25 pounds, depending on generation. First generation crosses (called F1 and F2) are generally larger than later crosses and have beautiful spotted coats in shades of brown, tan, and black. Later generations are further removed from their wild ancestor, yet retain the colors and patterns of earlier generations—they're just smaller and a bit more docile. Savannah cats are loyal, intelligent, and inquisitive kitties, but might not be the best choice for first-time cat owners. ",
      "fur_length": "short",
      "color": "brown",
      "hypoallergenic": "neutral",
      "grooming": "monthly",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "no",
      "child_compatability": "yes"
  },
  {
      "Breed": "Scottish Fold",
      "image": "https://cdn2.thecatapi.com/images/JQMGbOP3q.jpg",
      "description": "Scottish fold cats make great, affectionate pets that thrive on human interaction without being too demanding for your constant attention. They have a charmingly unique appearance due to their ear carriage, round heads and eyes, and thick legs and tail. Scottish folds are rare felines, prized for their huggable good looks and sweet personalities. Sporting round heads with tight, forward-facing folded ears and large eyes, Scottish folds always draw a lot of attention. Scottish fold cats are a medium-sized cat breed weighing 6–12 pounds. They're low-maintenance and love being with their people more than anything else in the world. They're smart, too, and love playing games or chasing toys around the house.\r\n\r\nColor Options: Tortishell, Black, Brown, White, Red/Ginger, and Blue/Gray",
      "fur_length": "short",
      "color": "no_preference",
      "hypoallergenic": "allergic",
      "grooming": "weekly",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "Selkirk Rex",
      "image": "https://cdn2.thecatapi.com/images/B2YB13Ydq.jpg",
      "description": "Prized for its unusual curly coat, the Selkirk Rex cat is one of only four breeds of cat with wavy fur. This curly-haired cat has a warm, loving disposition and comes in both short- and long-haired versions. If you’ve always dreamed of owning a live Teddy bear, a Selkirk Rex cat may be for you. These large, huggable kitties have round heads, big eyes, and a plush, curly coat that comes in a host of colors and patterns (even their whiskers are curled!). Both long-haired and short-haired Selkirk Rex cats are available and equally treasured. This cat breed is intelligent, loving, easy-going, and gets along well with people and other animals. Developed in the 1980s, Selkirk Rex is not yet as common as some other breeds, but it’s definitely worth seeking out. \r\n\r\nColor Options: Black, Brown, White, Cream, Red/Ginger, and Blue/Gray",
      "fur_length": "all",
      "color": "no_preference",
      "hypoallergenic": "allergic",
      "grooming": "weekly",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "Siamese",
      "image": "https://cdn2.thecatapi.com/images/KCJeb66J2.jpg",
      "description": "Siamese cats are social, affectionate, clever animals who make loving and loyal pets. Described as being 'dog-like,' these kitties mesh well into most families. The Siamese cat is a bright, intelligent feline with a handsome appearance and charming personality who can't help but draw admirers wherever he goes. Siamese kittens typically cost anywhere between $250–$1,000 and are a fairly popular breed. In 2018, the Siamese was the 13th most registered cat breed with the Cat Fanciers' Association. With their affectionate (and chatty!) personalities, it's easy to see why they're so beloved.\r\n\r\nColor Options: Tortishell, Black, Brown, and Blue/Gray",
      "fur_length": "short",
      "color": "no_preference",
      "hypoallergenic": "neutral",
      "grooming": "monthly",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "Siberian",
      "image": "https://cdn2.thecatapi.com/images/HNNrk-UxN.jpg",
      "description": "Siberian cats are lovable and loyal family companions who get along well with children and other pets. Learn more about this rugged Russian cat breed.  Siberian cats are (as their name suggests) native to Siberia, a region of Russia known for long, harsh winters. Their rugged origins are reflected in their long, weatherproof triple coat and strong bodies. These alert and solidly built cats are somewhat kittenish in personality. This breed is sweet-natured and loves to cuddle. Siberians are totally devoted to their pet parents and generally get along well with children and other pets. Siberian kittens typically cost between $1,200 and $4,000, depending on pedigree and age. Why the high price tag? This breed is expensive due to their high demand and the relatively low number of purebred Siberian cats outside of Russia—so they're pretty rare in the U.S.\r\n\r\nColor Options: Black, Brown, White, Red/Ginger, Blue/Gray, and Cream",
      "fur_length": "long",
      "color": "no_preference",
      "hypoallergenic": "non_allergic",
      "grooming": "weekly",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "Singapura",
      "image": "https://cdn2.thecatapi.com/images/JBkP_EJm9.jpg",
      "description": "Singapura cats are high-energy, pint-sized pets with wide eyes, big ears, and playful personalities.  The Singapura (pronounced “sing-uh-poor-uh”) is the smallest breed of domesticated cats. However, these petite pets are known for packing a lot of personality into their tiny bodies. Singapuras are pretty much guaranteed to steal the show wherever they go. This playful breed thrives on attention—and they get quite a bit, thanks to their unusual appearance and playful temperament. Singapuras have saucer-shaped eyes, large ears, tiny frames, and the energy of a few larger cats combined. These small, strong cats make fun family members and close companions.",
      "fur_length": "short",
      "color": "cream",
      "hypoallergenic": "neutral",
      "grooming": "weekly",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "Snowshoe",
      "image": "https://cdn2.thecatapi.com/images/blr4iUu-b.jpg",
      "description": "Blending some of the best, rarest traits from the Siamese and the American shorthair, snowshoe cats are beautiful, devoted family companions. The snowshoe breed beautifully combines traits from both the Siamese and American shorthair. The result is this lovely cat who is simultaneously reminiscent of both sides of her lineage while remaining wholly unique. A medium-large, healthy, long-lived breed, the snowshoe is a devoted family companion and a cat who not only tolerates but openly indulges in the company and affection of her people.\r\n\r\nColor Options: Black Brown White, Red/Ginger, and Blue/Gray",
      "fur_length": "short",
      "color": "no_preference",
      "hypoallergenic": "neutral",
      "grooming": "periodically",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "Sokoke",
      "image": "https://www.dogalize.com/wp-content/uploads/2017/04/sokoke-cat.jpg",
      "description": "The Sokoke is a natural cat breed cat, which means they developed without the need for human intervention These felines are known for being athletic, intelligent, and sociable. Sokokes are super smart cats who, in many cases, can learn tricks and even play fetch. These felines are loving towards the humans in their life, but they need a lot of attention and do not fare well if left alone for long periods of the day. They make an excellent fit for families with children.",
      "fur_length": "short",
      "color": "brown",
      "hypoallergenic": "neutral",
      "grooming": "periodically",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "Somali",
      "image": "https://cdn2.thecatapi.com/images/EPF2ejNS0.jpg",
      "description": "Somali cats are far more than just the sum of their parts. This is a lively, beautiful, intelligent cat who revels in the company of humans and animals alike. Considering the Somali’s origin story, it can be easy to write off these beautiful cats as 'just' a long haired Abyssinian. But as any Somali cat owner will tell you, there’s so much more to the story. Somalis are brilliant, gregarious, tirelessly active cats who delight in learning tricks, bonding with humans and other animals alike, and exploring every inch of their environments. Delightfully curious and playful, the Somali cat will be a lifelong friend and companion who will do its best to ensure you never have a dull moment.",
      "fur_length": "long",
      "color": "red",
      "hypoallergenic": "allergic",
      "grooming": "monthly",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "Sphynx",
      "image": "https://cdn2.thecatapi.com/images/Y_z-aBHvf.jpg",
      "description": "Sphynx cats are famous for their (nearly) nude appearance, but there is so much more to these charming, intelligent, and affectionate cats.  The sphynx cat breed is striking and utterly unmistakable, thanks to their natural baldness. Their unconventional looks have gained the sphynx a fair share of fans-and a few who are less than impressed by the breed's nakedness. But no matter how you feel about their head-turning appearance, these clownish cats are intelligent, engaging, and devoted pets. The sphynx is a loving and friendly breed who craves your attention and affection-especially the scritches that come with your love. Because they're a relatively uncommon breed, these hairless cats can cost a pretty penny. If you're looking to buy a sphynx cat, get ready to dig deep into your wallet: A sphynx kitten from a reputable breeder usually costs between $1,500-$6,000, depending on pedigree.",
      "fur_length": "naked",
      "color": "no_preference",
      "hypoallergenic": "non_allergic",
      "grooming": "weekly",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "Thai",
      "image": "https://allaboutcats.com/wp-content/uploads/2020/10/Thai-cats.jpg",
      "description": "The Thai or Wichien Maat is a newly renamed but old cat breed, related to but distinct from the Western, modern-style Siamese cat. This natural breed is descended from the cats of Thailand, and, among various groups of breeders in different times and places has also been called the Old-Style Siamese. According to The International Cat Association: 'The Thai is the breed dedicated to preserving the native pointed cat of Thailand in as close to its original form as possible.' Compared to the modern-style, more extreme-featured Siamese, the traditional Thai breed have a much more moderate appearance.",
      "fur_length": "short",
      "color": "brown",
      "hypoallergenic": "neutral",
      "grooming": "weekly",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "Tiffany",
      "image": "https://cdn2.thecatapi.com/images/TR-5nAd_S.jpg",
      "description": "The Chantilly-Tiffany is a cat breed that started with a pair of chocolate-colored kittens of unknown origin. These felines are known for being affectionate, social, and talkative. This breed originally went by the name Foreign Longhair. The Chantilly-Tiffany is a cat who loves to be around humans and will form very strong bonds with the main people in their life. While the breed is exceptionally social and loving, this also means that they would not fare well with being left alone for long periods of the day. This cat definitely wants company all the time, whether that includes snuggling, playing, or even talking!",
      "fur_length": "long",
      "color": "brown",
      "hypoallergenic": "allergic",
      "grooming": "weekly",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "Tonkinese",
      "image": "https://cdn2.thecatapi.com/images/OTQ16PV9k.jpg",
      "description": "The Tonkinese is a mix of the Siamese and Burmese cat breeds and has a loving, affectionate personality.  Tonkinese is a mix of the Siamese and Burmese cat breeds and shares many qualities with those parent breeds. This striking feline has a charming appearance, with a pointed coat and bright, jewel-tone eyes. Attentive Tonks were born to be a companion breed. These kitties love to play with people and curl up in a warm lap at the end of the day. They have a lot of affection to give their pet parents and make a wonderful, loving addition to many homes and families.\r\n\r\nColor Options: Black, Brown, White, Red/Ginger, and Blue/Gray",
      "fur_length": "all",
      "color": "no_preference",
      "hypoallergenic": "neutral",
      "grooming": "weekly",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "Toyger",
      "image": "https://cdn2.thecatapi.com/images/2CL5AqIfV.png",
      "description": "With their bold striping and rolling gait, the toyger can make you feel like a tiger king in the comfort of your own living room. Toyger isn't a name that beats around the bush. Without even seeing one, you know right away this cat is supposed to look like a tiny tiger. A toy tiger, if you will. Created in the 1980s, the toyger is a cat bred specifically to replicate not only the striped markings of its jungle cat namesake, but other physical traits as well. This has resulted in a muscular, athletic cat with a rolling gait that looks like she'd be more at home in an Indian jungle than a living room. Never fear: These kitties were also bred to be friendly and social, and they love to be around their humans and other furry friends.",
      "fur_length": "short",
      "color": "brown",
      "hypoallergenic": "neutral",
      "grooming": "weekly",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "Turkish Angora",
      "image": "https://cdn2.thecatapi.com/images/cSzaNCgq2.jpg",
      "description": "With their high intelligence and gorgeous white fur, it’s easy to see why the Turkish Angora is a national treasure in their home country. Beloved in their native Turkey, the Turkish Angora is quite possibly the only domestic cat kept and raised in a zoo. For a time, these gorgeous, intelligent, regal cats were all thought to be deaf (more on that later) and were used so heavily in crossbreeding to build up the Persian breed, they were almost driven to extinction. While still a rare breed today, the Turkish Angora has a devoted following across the globe among people who want a soft, visually magnetic long-haired cat.\r\n\r\nColor Options: Black, White, Red/Ginger, and Blue/Gray",
      "fur_length": "long",
      "color": "no_preference",
      "hypoallergenic": "allergic",
      "grooming": "weekly",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  },
  {
      "Breed": "Turkish Van",
      "image": "https://cdn2.thecatapi.com/images/j9_ETlBMp.jpg",
      "description": "An ancient, naturally occurring breed, Turkish vans are treasured in their home country and renowned for their large, strong bodies as well as their propensity to swim. The Turkish van (pronounced “von”) is a naturally occurring cat breed that originated in the mountains of Turkey. Not to be confused with Turkey’s other cat export, the Turkish Angora (more on that later), the Turkish van is beloved by owners for their sturdy build, playful, active nature and for being one of the relatively rare breeds of cat that has an affinity for water.\r\n\r\nColor Options: Black, White, Red/Ginger, andCream",
      "fur_length": "long",
      "color": "no_preference",
      "hypoallergenic": "allergic",
      "grooming": "weekly",
      "energy": "yes",
      "playful": "yes",
      "affection": "yes",
      "independence": "yes",
      "dog_compatibility": "yes",
      "cat_compatability": "yes",
      "child_compatability": "yes"
  }
]

// 68 breed options
// image
// description of breed
// fur length
// color options
// hypoallergenic options
// grooming frequency options
// energy level options
// playfulness options
// independence level options
// cat breeds compatability with dogs option
// cat breeds  compatability with additional cats options
// cat breeds  compatability with children options


const seedCatBreeds = () => Cats.bulkCreate(catBreeds);

module.exports = seedCatBreeds;