const catFacts = [
    {"fact" : "Cats have 230 bones, while humans only have 206."},
    {"fact" : "Cats are nearsighted, but their peripheral vision and night vision are much better than that of humans."},
    {"fact" : "Cats can jump up to six times their length."},
    {"fact" : "Cats have nearly twice the amount of neurons in their cerebral cortex as dogs."},
    {"fact" : "Cats have the largest eyes relative to their head size of any mammal."},
    {"fact" : "Cats make very little noise when they walk around. The thick, soft pads on their paws allow them to sneak up on their prey — or you!"},
    {"fact" : "Cats walk like camels and giraffes: They move both of their right feet first, then move both of their left feet. No other animals walk this way."},
    {"fact" : "Some cats are ambidextrous, but 40 percent are either left- or right-pawed."},
    {"fact" : "There are cats who have more than 18 toes. These extra-digit felines are referred to as being 'polydactyl'."},
    {"fact" : "A cat with a question-mark-shaped tail is asking, “Want to play?”"},
    {"fact" : "According to Wilde, a slow blink is a “kitty kiss.” This movement shows contentment and trust."},
    {"fact" : "Cats have a unique “vocabulary” with their owner — each cat has a different set of vocalizations, purrs and behaviors."},
    {"fact" : "Cats have up to 100 different vocalizations — dogs only have 10."},
    {"fact" : "Cats mark you as their territory when they rub their faces and bodies against you, as they have scent glands in those areas."},
    {"fact" : "Hissing is defensive, not aggressive, says Wilde. 'It’s an expression of fear, stress or discomfort of a threatened cat communicating ‘stay away,'' she says."},
    {"fact" : "If your cat approaches you with a straight, almost vibrating tail, this means that she is extremely happy to see you."},
    {"fact" : "Kneading — which some people refer to as 'making biscuits' — is a sign of contentment and happiness. Cats knead their mothers when they are nursing to stimulate the let-down of milk."},
    {"fact" : "When a cat flops over and exposes his belly, it’s not always an invitation for a belly rub. A cat does this when he’s relaxed and showing trust."},
    {"fact" : "When cats hit you with retracted claws, they’re playing, not attacking."},
    {"fact" : "When dogs wag their tails, they may be expressing happiness. But this isn’t the case for cats! When your cat wags her tail, it’s her way of warning you that you are getting on her last nerve."},
    {"fact" : "Your cat drapes its tail over another cat, your dog, or you as a symbol of friendship."},
    {"fact" : "Cats are very fussy about their water bowls; some prefer to ignore their bowls entirely in favor of drinking from the sink faucet."},
    {"fact" : "Cats groom other cats — and sometimes people — in a ritual called allogrooming."},
    {"fact" : "Cats like to sleep on things that smell like their owners, such as their pillows and dirty laundry (ick!)."},
    {"fact" : "Cats often attack your ankles when they’re bored."},
    {"fact" : "Certain cats go crazy for foods you wouldn’t expect, like olives, potato chips, and the hops in beer."},
    {"fact" : "For some reason, cats really dislike citrus scents."},
    {"fact" : "If you can’t find your cat, you should look in a box or a bag, as these are some of their favorite hiding spots!"},
    {"fact" : "When cats climb a tree, they can't go back down it head first. This is because their claws are facing the same way, instead, they have to go back down backward."},
    {"fact" : "A group of cats is called a “clowder.”"},
    {"fact" : "According to a Hebrew legend, God created cats after Noah prayed for help in protecting the food stores on the Ark from being eaten by rats. In return, God made a lion sneeze and out came a pair of cats. "},
    {"fact" : "Cats are actually more popular in the United States than dogs are. There are around 88 million pet cats versus 75 million pet dogs."},
    {"fact" : "Cat's can't taste sweetness. Scientists believe it's due to a genetic mutation that affects key taste receptors. "},
    {"fact" : "In Japan, cats are thought to have the power to turn into super spirits when they die. This may stem from the Buddist believe that cats are temporary resting places for powerful and very spiritual people. "},
    {"fact" : "Europe introduced cats into the Americas as a form of pest control in the 1750s."},
    {"fact" : "There are up to 70 million feral cats in the United States alone. A good reason to spay and neuter your pets! "},
    {"fact" : "In Holland’s embassy in Moscow, Russia, the staff noticed that the two Siamese cats kept meowing and clawing at the walls of the building. Their owners finally investigated, thinking they would find mice. Instead, they discovered microphones hidden by Russian spies. The cats heard the microphones when they turned on. Instead of alerting the Russians that they found said microphones, they simply staged conversations about delays in work orders and suddenly problems were fixed much quicker! "},
    {"fact" : "Cats only meow as a way to communicate with humans. "},
    {"fact" : "Cats can recognize your voice. So yes, they are just ignoring you. "},
    {"fact" : "The oldest cat video dates back to 1894 and is called 'Boxing Cats'"},
    {"fact" : "Cats and humans have nearly identical sections of the brain that control emotions.  "},
    {"fact" : "When a family cat died in ancient Egypt, family members would shave off their eyebrows as a sign of mourning. "},
    {"fact" : "Cats can move both ears separately and about 180 degrees around."},
    {"fact" : "While cats are seen as having a lower social IQ then dogs, they can solve much more difficult cognitive problems. When they feel like it of course."},
    {"fact" : "It was illegal to kill cats in Ancient Egypt. Not only were cats seen as an icon for Bast, the Goddess of Protection, but they were also very effective in keeping rats at bay. It was seen as a civil dis-service to kill them and often resulted in the death penalty. "},
    {"fact" : "Abraham Lincoln kept three cats in the white house. After the civil war was over, Lincoln found 3 kittens whose mother had died and took them in as his own. "},
    {"fact" : "Cat's, as well as other animals' noses,  have their own unique print, much like a humans fingerprint."},
    {"fact" : "When cats don't cover their poop, it is seen as a sign of aggression, meaning they don't fear you."},
    {"fact" : "Cats use their whiskers to determine if they can fit through a small space. The bigger the cat, the longer the whiskers will likely be."},
    {"fact" : "The Egyptian Mau is one of, if not the oldest domesticated cat breed. "},
    {"fact" : "When cats bring you a dead bird or a mouse, it's not a sign of affection but instead to let you know you suck at hunting. Maybe it's a sign of affection, making sure you don't starve but still! "},
    {"fact" : "Only 86% of U.S. Cats are spayed or neutered."},
    {"fact" : "Around only 24% of cats who enter a shelter end up getting adopted. (Spay and neuter your pets!) "},
    {"fact" : "In just 10 years one female cat could produce around 49,000 kittens. Another reason to spay and neuter your pets and help support Trap-Neuter-Release programs. "},
    {"fact" : "Cats spend nearly 1/3rd of their lives cleaning themselves. "},
    {"fact" : "They also spend nearly 1/3rd of their lives sleeping."},
    {"fact" : "Blacks cats are often seen as bad luck in North American whereas, in the Uk and Australia, they are seen as good luck. "},
    {"fact" : "A Cat's spine is so flexible because it's made up of 53 loosely fitting vertebrae. Humans only have 34. "},
    {"fact" : "A Cat's jaw can't move sideways. "},
    {"fact" : "When cats walk their back paws step almost exactly in the same place as the front paws did beforehand, this keeps noise to a minimum and limits visible tracks."},
    {"fact" : "Ever wonder why catnip lulls felines into a trance? The herb contains several chemical compounds, including one called nepetalactone, which a cat detects with receptors in its nose and mouth."},
    {"fact" : "More than half of the world’s felines don’t respond to catnip. Scientists still don’t know quite why some kitties go crazy for the aromatic herb and others don’t, but they have figured out that catnip sensitivity is hereditary. If a kitten has one catnip-sensitive parent, there’s a one-in-two chance that it will also grow up to crave the plant. And if both parents react to 'nip, the odds increase to at least three in four."},
    {"fact" : "The oldest cat ever lived for 38 years. Creme Puff of Austin, TX was born in August of 1967 and passed away in August of 2005. He still holds the Guinness World Record for oldest cat ever. "},
    {"fact" : "The musical Cats is based on a collection of T.S. Eliot poems called 'Old Possum’s Book of Practical Cats.'"},
    {"fact" : "A train station in Southeastern Japan is presided over by an adorable 'stationmaster': a 6-year-old calico cat named Nitama."},
    {"fact" : "Polydactyl cats refer to cats with 6 toes on their front paws."},
    {"fact" : "Approximately 200 feral cats roam the grounds of Disneyland, where they help control the amusement park’s rodent population. They’re all spayed or neutered, and park staffers provide them with medical care and extra food. "},
    {"fact" : "The Hungarian word for 'quotation marks,' macskaköröm, literally translates to 'cat claws.'"},
    {"fact" : "Cats can drink seawater! Their kidneys are able to filter salt out of water, something humans can't do."},
    {"fact" : "Contrary to public belief, adult cats shouldn't be given milk as most are lactose intolerant. After a kitten is weaned, the lactase enzyme, which is used to break down lactose,  starts to disappear. Giving your cat milk can cause an upset stomach and other tummy troubles. "},
    {"fact" : "Cats have both short term and long term memory. This means that they can remember, short term, up to 16 hours ago. Cats have both short term and long term memory. This means that they can remember, short term, up to 16 hours ago. "},
    {"fact" : "Scientist suggest that a cat's purr is a method of self-healing! "},
    {"fact" : "Cats make about 100 different sounds. Dogs make only about 10."},
    {"fact" : "There are 473 taste buds on a cat's tongue!"},
    {"fact" : "The technical term for a cat’s hairball is a 'bezoar.'"},
    {"fact" : "When a cat chases its prey, it keeps its head level. Dogs and humans bob their heads up and down."},
    {"fact" : "There are more than 500 million domestic cats in the world, with approximately 40 recognized breeds."},
    {"fact" : "Approximately 24 cat skins can make a coat"},
    {"fact" : "While it is commonly thought that the ancient Egyptians were the first to domesticate cats, the oldest known pet cat was recently found in a 9,500-year-old grave on the Mediterranean island of Cyprus. This grave predates early Egyptian art depicting cats by 4,000 years or more"},
    {"fact" : "During the time of the Spanish Inquisition, Pope Innocent VIII condemned cats as evil and thousands of cats were burned. Unfortunately, the widespread killing of cats led to an explosion of the rat population, which exacerbated the effects of the Black Death.["},
    {"fact" : "The first cat in space was a French cat named Felicette (a.k.a. “Astrocat”) In 1963, France blasted the cat into outer space. Electrodes implanted in her brains sent neurological signals back to Earth. She survived the trip."},
    {"fact" : "Approximately 40,000 people are bitten by cats in the U.S. annually."},
    {"fact" : "A cat’s hearing is better than a dog’s. And a cat can hear high-frequency sounds up to two octaves higher than a human."},
    {"fact" : "A cat can travel at a top speed of approximately 31 mph (49 km) over a short distance."},
    {"fact" : "A cat usually has about 12 whiskers on each side of its face."},
    {"fact" : "Perhaps the most famous comic cat is the Cheshire Cat in Lewis Carroll’s Alice in Wonderland. With the ability to disappear, this mysterious character embodies the magic and sorcery historically associated with cats."},
    {"fact" : "In the original Italian version of Cinderella, the benevolent fairy godmother figure was a cat."},
    {"fact" : "The little tufts of hair in a cat’s ear that help keep out dirt direct sounds into the ear, and insulate the ears are called 'ear furnishings.'"},
    {"fact" : "The ability of a cat to find its way home is called “psi-traveling.” Experts think cats either use the angle of the sunlight to find their way or that cats have magnetized cells in their brains that act as compasses."},
    {"fact" : "Cats hate the water because their fur does not insulate well when it’s wet. The Turkish Van, however, is one cat that likes swimming. Bred in central Asia, its coat has a unique texture that makes it water resistant."},
    {"fact" : "Researchers believe the word “tabby” comes from Attabiyah, a neighborhood in Baghdad, Iraq. Tabbies got their name because their striped coats resembled the famous wavy patterns in the silk produced in this city."},
    {"fact" : "Some Siamese cats appear cross-eyed because the nerves from the left side of the brain go to mostly the right eye and the nerves from the right side of the brain go mostly to the left eye. This causes some double vision, which the cat tries to correct by “crossing” its eyes."},
    {"fact" : "Some cats have survived falls of over 65 feet (20 meters), due largely to their “righting reflex.” The eyes and balance organs in the inner ear tell it where it is in space so the cat can land on its feet. Even cats without a tail have this ability.["},
    {"fact" : "The smallest pedigreed cat is a Singapura, which can weigh just 4 lbs (1.8 kg), or about five large cans of cat food. The largest pedigreed cats are Maine Coon cats, which can weigh 25 lbs (11.3 kg), or nearly twice as much as an average cat weighs."},
    {"fact" : "The most popular pedigreed cat is the Persian cat, followed by the Main Coon cat and the Siamese cat."},
    {"fact" : "Many Egyptians worshipped the goddess Bast, who had a woman’s body and a cat’s head."},
    {"fact" : "The biggest wildcat today is the Siberian Tiger. It can be more than 12 feet (3.6 m) long (about the size of a small car) and weigh up to 700 pounds (317 kg)."},
    {"fact" : "Most cats give birth to a litter of between one and nine kittens. The largest known litter ever produced was 19 kittens, of which 15 survived.["},
    {"fact" : "Researchers are unsure exactly how a cat purrs. Most veterinarians believe that a cat purrs by vibrating vocal folds deep in the throat. To do this, a muscle in the larynx opens and closes the air passage about 25 times per second."},
    {"fact" : "The group of words associated with cat (catt, cath, chat, katze) stem from the Latin catus, meaning domestic cat, as opposed to feles, or wild cat."},
    {"fact" : "The first commercially cloned pet was a cat named 'Little Nicky.' He cost his owner $50,000, making him one of the most expensive cats ever."},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""},
    {"fact" : ""}
  ]